### ISSUE TITLE
[NEW]: FTX Foundation and Future Fund and grantees

### ISSUE THREAD

**Issue by morrellk** [molly/ftx-contagion#12]
### Details

This is a general area that isn't included, not sure if it should be. My understanding is that FTX Foundation was/is a philanthropic arm of FTX, and Future Fund is one part of it. They have made grants to a bunch of different companies and people. Some grantees may be concerned about whether grants will be clawed back, but in addition, I imagine the loss of that funding stream could make continued operation difficult in some cases.

### Links

https://ftxfoundation.org/about/
https://ftxfuturefund.org/our-grants/

**Comment by molly** [comment]
Keeping #13 as the tracking issue for this suggestion
