### ISSUE TITLE
[NEW]: LUNO

### ISSUE THREAD

**Issue by theowinter** [molly/ftx-contagion#3]
### Details

LUNO is an exchange and wallet app, originating in ZA. They offer a "savings product" through Genesis, who has locked withdrawals. LUNO does not guarantee the Genesis funds, but they claim they have made other arrangements to restore customer funds on their own platform, likely from own equity (speculation). One to watch. They are audited by Mazars, a South African law firm in good standing.

### Links

https://discover.luno.com/an-update-on-lunos-savings-wallet/

**Comment by molly** [comment]
I'll keep an eye on it, but to date it doesn't sound like we can be sure they've suffered losses.
